
import Navbar from "../../../Components/main/Navbar";
import StarsCanvas from "../../../Components/main/StarBackground";
import { StockProvider } from "../context/Stock/stockContext";
export const metadata = {
  title: "FINFY : Market Stock Data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>FINFY : Market Stock Data</title>
      <body
        className={`$(inter.className) dark:bg-[#030014] bg-current overflow-y-scroll overflow-x-hidden w-[100vw] h-[full]`}
      >
        <StockProvider>
        <Navbar />
          <StarsCanvas />
          {children}
          {modal}
        </StockProvider>

      </body>
    </html>
  );
}
